import { motion } from "framer-motion";
import SectionHeading from "../components/ui/SectionHeading";
import GlassCard from "../components/ui/GlassCard";
import { fadeUp } from "../lib/motionVariants";

const SECTIONS = [
  {
    title: "Interpretation and Definitions",
    body: `The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\nAccount means a unique account created for You to access our Service or parts of our Service.\n\nAffiliate means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n\nCompany (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to oryntisapp, 525 Market Street, San Francisco, CA 94102, USA.\n\nCookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.\n\nCountry refers to: California, United States\n\nDevice means any device that can access the Service such as a computer, a cell phone or a digital tablet.\n\nPersonal Data (or "Personal Information") is any information that relates to an identified or identifiable individual.\n\nService refers to the Website.\n\nService Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n\nUsage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n\nWebsite refers to oryntisapp, accessible from http://oryntisapp.com/.\n\nYou means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
  },
  {
    title: "Collecting and Using Your Personal Data",
    body: `While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n- Email address\n- First name and last name\n- Phone number\n\nUsage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\nWe may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.`,
  },
  {
    title: "Tracking Technologies and Cookies",
    body: `We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:\n\nCookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.\n\nWeb Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.\n\nCookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.\n\nWhere required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool or through Your browser/device settings.\n\nWe use both Session and Persistent Cookies for the purposes set out below:\n\nNecessary / Essential Cookies — Type: Session Cookies — Administered by: Us — Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.\n\nCookies Policy / Notice Acceptance Cookies — Type: Persistent Cookies — Administered by: Us — Purpose: These Cookies identify if users have accepted the use of cookies on the Website.\n\nFunctionality Cookies — Type: Persistent Cookies — Administered by: Us — Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.`,
  },
  {
    title: "Use of Your Personal Data",
    body: `The Company may use Personal Data for the following purposes:\n\n- To provide and maintain our Service, including to monitor the usage of our Service.\n- To manage Your Account: to manage Your registration as a user of the Service.\n- For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.\n- To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.\n- To provide You with news, special offers, and general information about other goods, services and events which We offer unless You have opted not to receive such information.\n- To manage Your requests: To attend and manage Your requests to Us.\n- For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.\n- For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.\n\nWe may share Your Personal Data in the following situations:\n\n- With Service Providers: We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.\n- For business transfers: We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.\n- With Affiliates: We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.\n- With business partners: We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.\n- With other users: If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.\n- With Your consent: We may disclose Your Personal Data for any other purpose with Your consent.`,
  },
  {
    title: "Retention of Your Personal Data",
    body: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.\n\nWhere possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data.\n\nAccount Information — User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.\n\nCustomer Support Data — Support tickets and correspondence: up to 24 months from the date of ticket closure. Chat transcripts: up to 24 months for quality assurance and staff training purposes.\n\nUsage Data — Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection. Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.\n\nWe may retain Personal Data beyond the periods stated above for different reasons: legal obligation, legal claims, Your explicit request, or technical limitations in backup systems.\n\nWhen retention periods expire, We securely delete or anonymize Personal Data. Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule.`,
  },
  {
    title: "Transfer of Your Personal Data",
    body: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.\n\nWhere required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place.`,
  },
  {
    title: "Delete Your Personal Data",
    body: `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.\n\nOur Service may give You the ability to delete certain information about You from within the Service.\n\nYou may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.\n\nPlease note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.`,
  },
  {
    title: "Disclosure of Your Personal Data",
    body: `Business Transactions — If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\nLaw enforcement — Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.\n\nOther legal requirements — The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: comply with a legal obligation; protect and defend the rights or property of the Company; prevent or investigate possible wrongdoing in connection with the Service; protect the personal safety of Users of the Service or the public; protect against legal liability.`,
  },
  {
    title: "Security of Your Personal Data",
    body: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.",
  },
  {
    title: "Children's Privacy",
    body: "Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.",
  },
  {
    title: "Links to Other Websites",
    body: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
  },
  {
    title: "Changes to this Privacy Policy",
    body: 'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
  },
  {
    title: "Contact Us",
    body: "If you have any questions about this Privacy Policy, You can contact us by email: contact@oryntisapp.com",
  },
];

export default function Privacy() {
  return (
    <div className="mx-auto max-w-3xl px-6 pb-24 pt-28 lg:px-8">
      <SectionHeading eyebrow="Legal" headline="Privacy Policy" />

      <p className="mt-4 font-mono text-xs tracking-wide text-foreground-subtle">
        Last updated: July 16, 2026
      </p>

      <p className="mt-4 text-sm leading-relaxed text-foreground-muted">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
        of Your information when You use the Service and tells You about Your privacy rights and how
        the law protects You. We use Your Personal Data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in accordance with this Privacy
        Policy. This Privacy Policy has been created with the help of the TermsFeed Privacy Policy
        Generator.
      </p>

      <motion.div
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.05 }}
        variants={fadeUp}
        className="mt-10"
      >
        <GlassCard interactive={false} className="p-8 sm:p-10">
          <div className="prose prose-invert max-w-none space-y-8">
            {SECTIONS.map((s) => (
              <div key={s.title}>
                <h3 className="text-base font-semibold tracking-tight text-foreground">{s.title}</h3>
                {s.body.split("\n\n").map((paragraph, i) => (
                  <p key={i} className="mt-2 text-sm leading-relaxed text-foreground-muted whitespace-pre-line">
                    {paragraph}
                  </p>
                ))}
              </div>
            ))}
          </div>
        </GlassCard>
      </motion.div>
    </div>
  );
}
